### ISSUE TITLE
Pressing enter to create a [[double bracket]]

### ISSUE THREAD

**Issue by santiyounger** [vimwiki/vimwiki#892]
Hey,

I'm new to github, apologies if this is not properly structure, if you need more info let me konw. 
**This is probably an easy solve but I am stuck trying to solve it. Any help or suggestions are greatly appreciated.**
I'm on vimwiki Stable Version 2.5.
I recently moved my whole set up from ubuntu to manjaro kde plasma. Vimwiki is my post important vim plug-in and I absolutely love it.

**I rebuilt my vimrc with all the plug-ins. vimwiki seems to work alright, the only problem I have is the ENTER fucnction.**

When I press enter on some text to create a new vimwiki markdown file. I get this kind of situation.

**[new note](new note)**

I used to have this kind of result

**[[new note]]**

I really want to go back to the double bracket and I don't know why that changed since everything in my vimrc is the same.

I istanlled vim wiki with Plug like this:

`Plug 'vimwiki/vimwiki'`

Here I'll copy everything I have in my vimrc regarding vimwiki.

Vimrc
```
". .............................................................................
  Vim wiki
"............................................................................

"set nocompatible
filetype plugin on
syntax on

"".... vimwiki with markdown support
"let g:vimwiki_ext2syntax = {'.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
"".... helppage -> :h vimwiki-syntax

let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]

```

**Comment by sharingtom** [comment]
Hi, I just want to chime in and say that I would also very much prefer the double brackets in Markdown files.

If Markdown style links are the default for the Markdown syntax, would you consider adding something like _g:vimwiki_link_format_, or an option to _g:vimwiki_list_?

**Comment by Nudin** [comment]
> ****
> 
> I really want to go back to the double bracket and I don't know why that changed since everything in my vimrc is the same.

We just released v2.5 a few days ago, so you likely have upgraded vimwiki without realizing when moving to the new setup.
I am however a bit confused, I tried with 2.3, 2.4.1 and 2.5 and in all three cased the markdown syntax `[text](text)` is used.

@ranebrown @tinmarino: Do you know if there was a change in 2.5 that affects this?

@sharingtom: Do you also have a regression (meaning previously double brackets in Markdown worked) or is this "just" a feature request?

@santiyounger: Can you try downgrading to 2.4 and check if it works then again?
```
Plug 'vimwiki/vimwiki', { 'tag': 'v2.4.1' }
```
and `:PlugClean` then `:PlugInstall` should do it.

**Comment by tinmarino** [comment]
> Do you know if there was a change in 2.5 that affects this?

No. I've always got `[text](text)` to and from blame, it seems to me that all lines concerning `ENTER` key were there in 2017 

The stack trace for someone wanting to create an PR for an option:
[vimwiki#base#follow_link](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/base.vim#L1302) ->
[vimwiki#base#normalize_link](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/base.vim#L2308) ->
vimwiki#vars#get_syntaxlocal  ->
vimwiki#vars#populate_syntax_vars ->
[let g:vimwiki_syntax_variables[a:syntax].rxWikiLink = g:vimwiki_global_vars.rx_wikilink_prefix.
](https://github.com/vimwiki/vimwiki/blob/619f04f89861c58e5a6415a4f83847752928252d/autoload/vimwiki/vars.vim#L689)

Where you can see that the issue author would like a link format that the dev have called `rxWikiLink ` or latter `rxWikiLink0` (for markdown). And the one we (I like to) use is called `WikiLink1Template2`.

__More:__
* [vars.vim](https://github.com/vimwiki/vimwiki/blob/master/autoload/vimwiki/vars.vim) is well commented and is the target.
* `:h h vimwiki-syntax-links`

**Comment by sharingtom** [comment]
It’s a feature request from my side.

A few days ago I found Obsidian, which has a lot of the functionality of Vimwiki – minus Vim – but uses Markdown and square bracket links. It would be great to be able to easily collaborate on wikis with non-Vim users. I absolutely love Vimwiki, but convincing most non-technical people to learn Vim for wiki collaboration is just not an option.

While square brackets can be added manually in Vimwiki to create the links, the Enter link formatting would be a quality of life improvement for me. I’m not at a skill level where I can make a PR to make it work. Not yet at least.

**Comment by santiyounger** [comment]
Hey @Nudin, **thank you so much for your kind reply.** I tried installing  v2.4.1, unfortunately it is still showing this format [text](text)
 **I did it as instructed :**
Plug 'vimwiki/vimwiki', { 'tag': 'v2.4.1' }
with :PlugClean then :PlugInstall 

Since I completely wiped my ubuntu set up into my new manjaro KDE I have no way of finding what was the exact version I was on.
To me things were working perfect with the [[double braket]] in a previous version.
**If anyone knows which version allows this, I'd be more than happy to downgrade to that version.**

I fully agree with @sharingtom with this **being a really essential function.**

More thank anything **I want to truly thank you for making such an amazing tool,** and for using your valuable time to help those of us who use it everyday, you guys are amazing.

**Comment by santiyounger** [comment]
@tinmarino **Thanks a lot for your reply,** unfortunately my skill level didn't allow me to fully understand your suggestions. I can comfortably modify things in my .vimrc file. But things such as creating a PR I don't fully understand what that means.

If you can put it in simple terms that would be much appreciated, **I'm happy with a workaround solution if needed.**
Thanks a lot!

**Comment by sharingtom** [comment]
I know that the question wasn't directed at me, but PR is short for [pull request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

If you modify the Vimwiki codebase (not just the .vimrc) to add the double square bracket functionality to the Markdown syntax, a pull request is basically how to ask the maintainers of Vimwiki here on GitHub to add the change to the main codebase and thus make it available to everyone.

I would also like to thank everyone who is a part of making Vimwiki. For all its simplicity (in use) it is wonderfully powerful.

**Comment by santiyounger** [comment]
@sharingtom Thanks, great explanation I appreciate it! I'll keep looking for solutions to this situation if I find one I'll post it here! Thanks guys

**Comment by tinmarino** [comment]
Read the commit message of the commit referencing this issue. (The last one: they often break tests and I commit amend in my repo)

Adding in `vars.vim` the function: `normalize_syntax_settings(syntax)`

__Fixed__: Workaround or better say ...

## undocumented solution :
```
let g:vimwiki_syntax_variables.markdown.Link1 = vimwiki#vars#get_global('WikiLinkTemplate1')
```

This may change and get documented. Meanwhile, follow the changes in [test/link_creation.vader](https://github.com/vimwiki/vimwiki/blob/dev/test/link_creation.vader) or grep the issue number in the repo

**Comment by nelai1** [comment]
I observed the same change in behaviour.
Removing: `'syntax':'markdown'` from the vimwiki_list variable in the .vimrc:
```
let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]
```
 changed the link creation back to `[[...]]`-syntax when pressing enter

**Comment by ericboehs** [comment]
Yeah that does fix it but now everything else is broke in regards to markdown formatting. 😄

**Comment by Thomascountz** [comment]
After installing the `dev` branch and updating the config, I'm receiving this error:

```
Error detected while processing /Users/thomascountz/.config/nvim/init.vim:
line  123:
E121: Undefined variable: g:vimwiki_syntax_list
```

This is the relevant line in my `.vimrc` (actually `.config/nvim/init.vim`)
```vim
let g:vimwiki_syntax_variables.markdown.Link1 = vimwiki#vars#get_global('WikiLinkTemplate1')
```

I'm not super familiar with vimscript, so I may not be instantiating the dict correctly? 

I modeled the configuration off of the tests here:

https://github.com/vimwiki/vimwiki/blob/a6878015e6180532d7e5eb13266a5810742819c5/test/link_creation.vader#L9-L32

And in the new docs:

https://github.com/vimwiki/vimwiki/blob/a6878015e6180532d7e5eb13266a5810742819c5/doc/vimwiki.txt#L2850-L2863

Thank you so much for your time and assistance!

**Comment by Thomascountz** [comment]
On the `dev` branch, in my `.vimrc` (actually `.config/nvim/init.vim`), this is what worked for me:

```vim
let g:vimwiki_syntaxlocal_vars['markdown']['Link1'] = g:vimwiki_syntaxlocal_vars['default']['Link1']
```

Now when I have the following markdown file:

```markdown
hello, world
```

and I press `ee<CR>`

I see this:

```markdown
hello, [[world]]
```

**Comment by p3palazzo** [comment]
> ```viml
> :let g:vimwiki_syntaxlocal_vars['markdown']['Link1'] = g:vimwiki_syntaxlocal_vars['default']['Link1']
> ```

I get a `Undefined variable: g:vimwiki_syntaxlocal_vars` error when trying this with an open Vimwiki file (where the filetype is properly set to Vimwiki). Other `let g:vimwiki...` commands work fine. Using version 2.5. Is this a bleeding-edge feature only available in the dev branch?

**Comment by alexcardell** [comment]
@ericboehs that autocmd still throws an error for me because the dict is not initialised. Perhaps a custom vimwiki autocmd would be useful for this (though at that point is it just easier to configure it in vimwiki_list?)

**Comment by ericboehs** [comment]
@alexcardell I'm not sure I'm understanding your problem but I'm guessing you're on the `master` branch instead of `dev`. This feature is exclusive to the dev branch for now.

**Comment by alexcardell** [comment]
Ah no, my apologies, I was on dev but the issue was with my autocmds; Just the quirks of my setup, I should have tried it with a clean vim before commenting.

**Comment by ericboehs** [comment]
Yeah, my solution is definitely a hack. I think the official solution should be a vimwiki_list config var.

**Comment by omichaelo** [comment]
> ```viml
> :let g:vimwiki_syntaxlocal_vars['markdown']['Link1'] = g:vimwiki_syntaxlocal_vars['default']['Link1']
> ```

This workaround works for me. However, `:VimwikiBacklinks` doesn't seem to recognize the double bracket links if the `syntax` is still set to `markdown`.

**Comment by lyndhurst** [comment]
First of all, thanks for all the tips shared here.

Adding an autocmd as suggested by @ericboehs works for me too on the `dev` branch, but I was wondering if anyone found a workaround for the `:VimwikiBacklinks` issue pointed by @omichaelo that I am experiencing as well with that configuration.

**Comment by Pepedou** [comment]
Any update on this? I'm also using Obsidian and it'd be great to be able to have markdown with [[wikilinks]].

**Comment by jls83** [comment]
Howdy folks, I put together a hacky workaround to get the backlinks working with double-square bracket link syntax. It also supports the "standard" Markdown syntax (`[description](url)`), as the diary links seem to use that syntax even with the `g:vimwiki_syntaxlocal_vars` override. The commit on my local branch is linked here: https://github.com/jls83/vimwiki/commit/3726e49ff1ef6702828eda894a390b092b1e7c23

**Comment by SCassidy-UK** [comment]
> Any update on this? I'm also using Obsidian and it'd be great to be able to have markdown with [[wikilinks]].

Exactly, editing with vimwiki and reading in Obsidian would be a great workflow for me.

**Comment by trpdoran** [comment]
I'm experimenting with using Vimwiki with Obsidian, and am seeing this double bracket issue running the latest version of vimwiki. I came up with a workaround by placing the following in my .vimrc.

`augroup md_link " {
autocmd!
autocmd BufNewFile,BufFilePre,BufRead *.md let g:vimwiki_syntaxlocal_vars['markdown']['Link1'] = g:vimwiki_syntaxlocal_vars['default']['Link1']
augroup END " }
`

Now double brackets are inserted when hitting enter and Vimwiki BackLinks is working for me. My experience so far has been that using vim to edit and create files in my Obsidian directory is working.
